[versions]
kotlin = "2.4.10"
shadow = "9.6.1"
run-paper = "3.1.0"
paper = "26.2.build.+"
placeholderapi = "2.12.3"
vault = "1.7.1"
worldguard = "7.0.16"
worldedit = "7.3.18"
junit = "5.11.4"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
vault-api = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }
worldguard-bukkit = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }
worldguard-core = { module = "com.sk89q.worldguard:worldguard-core", version.ref = "worldguard" }
worldedit-core = { module = "com.sk89q.worldedit:worldedit-core", version.ref = "worldedit" }
worldedit-bukkit = { module = "com.sk89q.worldedit:worldedit-bukkit", version.ref = "worldedit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
